version: "3.9"

services:
  cai:
    build: .
    container_name: cai
    ports:
      - "5002:5000"
    volumes:
      - ./db:/app/db
    environment:
      # Flask
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - TZ=Europe/Paris

      # Sécurité / Auth
      - SECRET_KEY=ehfzehflhnzflzefhzeffoihi            # ⚠️ change-moi en prod
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=Lucas123  # ⚠️ mets un vrai mot de passe
      - DISABLE_DEFAULT_ADMIN_LOGIN=1
      - SESSION_COOKIE_SECURE=1

      # Base de données (SQLite montée sur ./db)
      - DATABASE_URL=sqlite:///../db/cai.db
